### ISSUE TITLE
Doxygen macro does not forward some args to the underlying rule

### ISSUE THREAD

**Issue by krakeusz** [TendTo/rules_doxygen#1]
Hey,

First of all, this project is a good piece of work! Running doxygen with `rules_doxygen` is much easier than telling Bazel to run the doxygen binary.

I currently struggle a bit with making the `doxygen` rules optional. I don't want documentation to be built when running eg. `bazel build ...`.

Typically, you would do [this](https://bazel.build/reference/be/common-definitions) by writing:
```starlark
doxygen(
    name = "doxygen",
    tags = ["manual"],
    # ...
)
```
But `doxygen` macro does not forward the `tags` to `_doxygen` rule. Actually, I can't set `target_compatible_with` in the `doxygen` macro because of a similar problem.

Would you consider forwarding `**kwargs` from `doxygen` to `_doxygen`? Both `tags` and `target_compatible_with` would be understood by the `_doxygen` rule automatically. That could solve these 2 issues and potentially more.

**Comment by TendTo** [comment]
Absolutely! Thank you for the suggestion!
