### ISSUE TITLE
Allow DOT_PATH injection

### ISSUE THREAD

**Issue by hofbi** [TendTo/rules_doxygen#2]
When using the graphviz dot binary, doxygen is not fully hermetic but uses the system `dot` coming from the `graphviz` package. However this can be configured in the `Doxyfile` via the `DOT_PATH` attribute.

I am currently thinking about the best way to do this, so let's look at the example from the README and the existing configuration option:

```
doxygen(
    name = "doxygen",   # Name of the rule, can be anything
    # more stuff
    configurations = [                              # Additional configurations to add to the Doxyfile
        "DOT_PATH = PATH_OF_THE_TARGET(@graphviz//:bin/dot)",
    ]
)
```

Assuming I have the dot binary available with `@graphviz//:bin/dot`, how could I get the path to it here in the configurations?

Alternatively, the rule could be extended with an argument and this could done in the [template substitution](https://github.com/TendTo/rules_doxygen/blob/0409ca215212938d7e500a70ad91e073734f14b8/doxygen.bzl#L14-L18). I think we would need something like `ctx.executable._dot.dirname + "/"` if adding an executable label to the rule.

What do you think? Do you have other ideas?

**Comment by TendTo** [comment]
That's a desirable feature I didn't really consider in the beginning. I made some experiments you can find in a [separate branch](https://github.com/TendTo/rules_doxygen/tree/feat/hermetic-dot), but in short, by adding an executable parameter `dot_executable` to the base rule, it seems it is possible to achieve your goal.
The result would be something like

```bzl
load("@doxygen//:doxygen.bzl", "doxygen")

# Assuming the `dot` binary is located in the same folder
filegroup(
    name = "dot_executable",
    srcs = select(
        {
            "@platforms//os:linux": ["dot"],
            "@platforms//os:macos": ["dot"],
            "@platforms//os:windows": ["dot"],
        },
        "Unsupported platform",
    ),
)

doxygen(
    name = "doxygen",
    srcs = glob([
        "*.h",
        "*.cpp",
        "*.sh",
    ]) + [":dot_executable"], # Ideally, this would be an external module, like "@graphviz//:bin/dot". It seems the repetition is necessary
    dot_executable = ":dot_executable", # Ideally, this would be an external module, like "@graphviz//:bin/dot"
    have_dot = True,
    project_name = "graphviz",
)
```

**Comment by hofbi** [comment]
Outstanding, thanks a lot. I just tested it and it works like a charm. I am all in to get this merged and up to BCR

**Comment by TendTo** [comment]
It would be nice to have a `@graphviz` on the BCR, but I'd say it is out of the scope of this module. For now I'll just provide support for it. And I guess the same approach could be extended to other external tools in the future if needed (e.g. DIA_PATH, PLANTUML_JAR_PATH)
