### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by kaycebasques** [TendTo/rules_doxygen#4]
Hello! Thanks for the helpful library. We're migrating pigweed.dev to a Bazel-based build and are looking into [offloading our Doxygen stuff](https://pwrev.dev/247192) to your rules. Do you have any cycles to add macOS support? Our team is pretty evenly split between Linux and macOS so support for both is very necessary for us. Thanks again.

**Comment by TendTo** [comment]
Hi, unfortunately I don't have easy access to a Mac OS machine, so I can't really test anything. That's the main reason I postponed support for the platform. I'm also not sure how well Bazel supports the `.dmg` file.

This said, the process for adding it should be pretty straightforward:

```bazel
# In the "extensions.bzl" file
# ...
        if ctx.os.name.startswith("windows"):
            doxygen_sha256 = "478fc9897d00ca181835d248a4d3e5c83c26a32d1c7571f4321ddb0f2e97459f"
        elif ctx.os.name == "macos":  # TODO: Update this to the correct version
            doxygen_sha256 = "0" * 64
        elif ctx.os.name == "linux":
            doxygen_sha256 = "db68ca22b43c3d7efd15351329db5af9146ab1ac7eaccd61a894fe36612da8fb"
        else:
            fail("Unsuppported OS: %s" % ctx.os.name)

        for attr in mod.tags.version:
            doxygen_version = attr.version if attr.version != "" else fail("Version must be specified")
            doxygen_sha256 = attr.sha256 if attr.sha256 != "" else "0" * 64

        doxygen_version_dash = doxygen_version.replace(".", "_")

        url = "https://github.com/doxygen/doxygen/releases/download/Release_%s/doxygen-%s.%s"
        if ctx.os.name.startswith("windows"):
            url = url % (doxygen_version_dash, doxygen_version, "windows.x64.bin.zip")
            # elif ctx.os.name == "macos": # TODO: support macos
            # url = url % (doxygen_version_dash, doxygen_version, "dmg")

        elif ctx.os.name == "linux":
            url = url % (doxygen_version_dash, doxygen_version, "linux.bin.tar.gz")
            strip_prefix = "doxygen-%s" % doxygen_version
        else:
            fail("Unsuppported OS: %s" % ctx.os.name)
# ...
```

and then

```bazel
# In the "doxygen.BUILD.bazel" file
# ...
filegroup(
    name = "executable",
    srcs = select({
        "@platforms//os:linux": ["bin/doxygen"],
        "@platforms//os:macos": ["doxygen"], # TODO: path to the executable in the extracted dmg folder
        "@platforms//os:windows": ["doxygen.exe"],
    }, "Unsupported platform"),
    visibility = ["//visibility:public"],
)
```

**Comment by TendTo** [comment]
By the way, this issue got me thinking that a possible workaround would be to support system-wide installation of doxygen. This is now supported in version `1.2.0` of the rules (as soon as it gets pushed in the archive). I'm not sure if it works for you: you would need to make sure the mac has the right version of doxygen installed. 
If you are only concerned about CI/CD pipelines, such as github actions, you may get some inspiration from how I did it in my ci file:
 https://github.com/TendTo/rules_doxygen/blob/6feebfeb51acfe9a87077e0cb8243b19f2fc6e28/.github/workflows/ci.yml#L28

**Comment by kaycebasques** [comment]
Thanks for responding and for the pointers. I requested a macOS loaner laptop from my work (which should be arriving today) so hopefully I can submit a PR this week.
