### ISSUE TITLE
Support Arm Mac

### ISSUE THREAD

**Issue by kaycebasques** [TendTo/rules_doxygen#8]
Doxygen started recently releasing native Apple Silicon builds: https://github.com/doxygen/doxygen/issues/10066#issuecomment-2483706108

Supporting this would solve the CI/CQ tryjob issues I described in https://github.com/TendTo/rules_doxygen/pull/6#issuecomment-2479509517

**Comment by kaycebasques** [comment]
My first instinct is to split the `mac` platform into `mac_arm` and `mac_intel`:

```
doxygen_extension.version(
    sha256 = "...",
    # url needs to point to github action artifact download link for now
    url = "...",
    platform = "mac_arm"
)

doxygen_extension.version(
    sha256 = "...",
    version = "1.9.6",
    platform = "mac_intel"
)
```

@TendTo also suggested exposing `executable` here https://github.com/doxygen/doxygen/issues/10066#issuecomment-2483832777

I think either would work for us but splitting the platforms into `mac_arm` and `mac_intel` would be a bit easier for me at the moment

**Comment by kaycebasques** [comment]
@TendTo re: your idea to expose `executable`, would this allow me to specify a different executable platform? I'm pretty sure that would work for us.

Re: the `rules_doxygen` API it seems like the proper way to expose these permutations might be:

```
doxygen_extension.version(
    executable = "...",
    os = "mac",
    arch = "aarch64",
)
```

**Comment by kaycebasques** [comment]
I left a comment in https://github.com/doxygen/doxygen/issues/10066 asking if they plan on releasing Doxygen 1.13.0 soon (and including the macOS ARM binary as part of the release). If they are, then it may be best to just wait for that. This issue is turning out to be complicated and I'm still figuring out what's the best course of action for Pigweed here.

**Comment by kaycebasques** [comment]
Doxygen confirmed that they don't have plans any time soon to provide official macOS ARM binary releases so I think that settles the issue. The path forward IMO is for `rules_doxygen` to allow users to provide their own per-platform executables

https://github.com/doxygen/doxygen/issues/10066#issuecomment-2494658631

**Comment by TendTo** [comment]
Ok, I think we may be close. There are 2 new configurable platforms, linux-arm and mac-arm, and you can now provide an executable in the configuration. It should be a Label pointing to it, and you may need a `@@` at the beginning if you are referring to the root module. 

I also took advantage of this and also introduced a very easy to fix breaking change, (just rename `doxygen_extension.version` -> `doxygen_extension.configuration`).
Let me know if this would work for you.

**Comment by kaycebasques** [comment]
Great, thank you! I'll provide an update later today.

**Comment by kaycebasques** [comment]
I'm not sure if whether I'm holding something wrong or it's something on the `rules_doxygen` end but I'll share my progress.

In `MODULE.bazel` I've rigged up the prototype workflow to download/extract binaries:

```
http_archive(
    name = "doxygen_linux_gcc",
    url = "https://kaycebasques.github.io/doxybin/20241125/ubuntu-gcc-release.zip",
    sha256 = "f479c0eed0b0de28f58c6c7997c38d282b7afadf73dd132199019e4ff7f100f2",
    type = "zip",
    build_file_content = """
filegroup(
    name = "files",
    srcs = ["doxygen"],
    visibility = ["//visibility:public"],
)
sh_binary(
    name = "executable",
    srcs = ["doxygen"],
    data = [":files"],
    visibility = ["//visibility:public"],
)
""",
)
```

`bazelisk run @doxygen_linux_gcc//:executable` works as expected

also in `MODULE.bazel` I've patched it to use latest code like so:

```
git_override(
    module_name = "rules_doxygen",
    commit = "b8758dd1f8d54b6024e05c181b0a6f35d57e91e6",  # presumably I just use last commit from the WIP PR?
    remote = "https://github.com/tendto/rules_doxygen.git",
)
doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
doxygen_extension.configuration(
    platform = "linux",
    executable = "@doxygen_linux_gcc//:executable",
)
```

Trying to build the docs with the self-provided binary however leads to this error:

```
ERROR: Traceback (most recent call last):
	File "/home/kayce/.cache/bazel/_bazel_kayce/9659373b1552c281136de1c8eeb3080d/external/rules_doxygen+/extensions.bzl", line 258, column 44, in _doxygen_extension_impl
		executables.append(str(ctx.path(Label(attr.executable))) if attr.executable != "" else "")
Error in path: Unable to load package for @@[unknown repo 'doxygen_linux_gcc' requested from @@rules_doxygen+]//:executable: The repository '@@[unknown repo 'doxygen_linux_gcc' requested from @@rules_doxygen+]' could not be resolved: No repository visible as '@doxygen_linux_gcc' from repository '@@rules_doxygen+'
ERROR: error evaluating module extension doxygen_extension in @@rules_doxygen+//:extensions.bzl
INFO: Elapsed time: 0.112s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching module extension doxygen_extension in @@rules_doxygen+//:extensions.bzl; starting
```

**Comment by TendTo** [comment]
Unfortunately I don't really understand all the details behind repository visibility at play here.
Based on my experimentation, try adding another `@` before the label for the executable. It would become `@@doxygen_linux_gcc//:executable`.

**Comment by kaycebasques** [comment]
@TendTo we switched production pigweed.dev over to Bazel yesterday! Planning on writing a blog post and saying thanks to you for implementing these critical features and being very helpful/receptive in general. LMK if you'd prefer me to not mention you in the post

**Comment by kaycebasques** [comment]
blog post is here: http://pigweed.dev/docs/blog/08-bazel-docgen.html
